# headers and icon 
title: Jinrui Han
info: MEng @ SJTU
icon-pic: assets/img/icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
